# -*- coding: utf-8 -*-
"""Dump the curated findings that exist ONLY in the live RocksDB store.

re_kb/README.md calls re_kb_data/ "a rebuildable RocksDB store" and gitignores
it. That is not true today: 24 hand-curated findings live there and in no
committed file. Applying the documented rebuild -- or deleting the data dir on
the strength of the README -- destroys them.

This writes them out as a normal seed file so the claim in the README becomes
true again.

    PYTHONIOENCODING=utf-8 python tools/re_kb/_dump_live_only.py
"""
import base64
import glob
import json
import os
import re
import urllib.request

URL = "http://127.0.0.1:8001/sql"
AUTH = "root:root"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "78_recovered_live_only.surql")

BS = chr(92)          # a literal backslash
ESCQ = BS + chr(39)   # backslash-apostrophe, spelled so no tool layer can eat it

SKIP = {"id"}


def sql(stmt):
    req = urllib.request.Request(URL, data=("USE NS re DB kb; " + stmt).encode("utf-8"),
                                 method="POST")
    req.add_header("Accept", "application/json")
    req.add_header("Authorization",
                   "Basic " + base64.b64encode(AUTH.encode()).decode())
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def rows(res):
    out = []
    for b in res if isinstance(res, list) else []:
        if isinstance(b, dict) and b.get("status") == "OK" and isinstance(b.get("result"), list):
            out.extend(b["result"])
    return out


def lit(v):
    """SurrealQL literal, BACKSLASH-escaped.

    Not doubled (''). That was the old seed convention and SurrealDB 3.1.4
    rejects it outright: "Unexpected token `a strand`". Because a .surql file
    is POSTed as one script, the parser then consumes the following statements
    as string content, returns 200, and every block reports OK -- so the file
    silently applies almost nothing. This function wrote 15 such escapes into
    the recovery seed, which meant the recovered findings could not have been
    restored from it.
    """
    if v is None:
        return "NONE"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        return "'" + json.dumps(v, ensure_ascii=False).replace(BS, BS + BS).replace("'", ESCQ) + "'"
    return "'" + str(v).replace(BS, BS + BS).replace("'", ESCQ) + "'"


def main():
    seed = set()
    for p in glob.glob(os.path.join(HERE, "*.surql")):
        seed |= set(re.findall(r"UPSERT\s+finding:([\w\d_]+)",
                               open(p, encoding="utf-8", errors="replace").read()))

    recs = rows(sql("SELECT * FROM finding;"))
    want = []
    for r in recs:
        ident = str(r.get("id", ""))
        slug = ident.split(":")[-1].strip("`⟨⟩")
        if slug.startswith("doc_") or slug in seed:
            continue
        want.append((slug, r))
    want.sort()

    edges = rows(sql(
        "SELECT record::id(in) AS a, record::id(out) AS b, "
        "record::tb(out) AS tb, meta::tb(id) AS e FROM cites, about;"))

    lines = [
        "-- " + "=" * 74,
        "-- 78: RECOVERED -- findings that existed only in re_kb_data/ (the",
        "-- gitignored RocksDB store) and in no committed file.",
        "--",
        "-- re_kb/README.md describes re_kb_data/ as \"a rebuildable RocksDB store\".",
        "-- That was not true when this file was generated: these %d curated" % len(want),
        "-- findings had no other home, so the documented rebuild procedure would",
        "-- have silently destroyed them. Generated by _dump_live_only.py.",
        "--",
        "-- Review the statuses. These predate the promotion rule in",
        "-- 77_epistemics.surql, so `confirmed` here means \"someone wrote",
        "-- confirmed\", not \"reproduction- or code-grade evidence is cited\".",
        "-- " + "=" * 74,
        "USE NS re DB kb;",
        "",
    ]

    for slug, r in want:
        sets = []
        for k in sorted(r):
            if k in SKIP:
                continue
            v = r[k]
            if v is None or v == "":
                continue
            sets.append("%s=%s" % (k, lit(v)))
        lines.append("UPSERT finding:%s SET\n  %s;" % (slug, ",\n  ".join(sets)))
        lines.append("")

    slugs = {s for s, _ in want}
    rel = [e for e in edges if e.get("a") in slugs]
    if rel:
        lines.append("-- ---- their edges " + "-" * 56)
        for e in rel:
            lines.append("RELATE finding:%s->%s->%s:%s;"
                         % (e["a"], e["e"], e["tb"], e["b"]))
        lines.append("")

    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("recovered %d findings + %d edges" % (len(want), len(rel)))
    print("-> %s" % OUT)
    for s, _ in want[:6]:
        print("   %s" % s)


if __name__ == "__main__":
    main()
